.TH SKAFF.CONF "5" "August 2016" \
"skaff (A CMake-based project scaffolding tool) 1.0" "Skaff Configuration"
.SH NAME
skaff.conf \-  Configuration file for Skaff
.SH SYNOPSIS
.BI $XDG_CONFIG_HOME /skaff/skaff.conf
.br
.BI $HOME /.config/skaff/skaff.conf
.SH DESCRIPTION
.SH AUTHOR
Written by Jiahui Xie.
.SH COPYRIGHT
Copyright \(co 2016 Jiahui Xie.
.br
Licensed and distributed under the BSD 2\-Clause License.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR skaff (1),
.BR skafftutorial (7)
.br

The website for
.B skaff
is hosted by github pages at <http://jhxie.github.io/skaff/>
