.TH SKAFFTUTORIAL "7" "July 2016" \
"skaff (A CMake-based project scaffolding tool) 1.0" "Skaff Manual"
.SH NAME
skafftutorial \- A tutorial introduction to Skaff
.SH DESCRIPTION
.SH AUTHOR
Written by Jiahui Xie.
.SH COPYRIGHT
Copyright \(co 2016 Jiahui Xie.
.br
Licensed and distributed under BSD 2\-Clause License.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
The website for
.B skaff
is hosted by github pages at <http://jhxie.github.io/skaff/>
